Repository Talk-Pick/TalkPick_Server, pull requests merged in 2025-08, with the labels that each got.

#172 [Refactor] Centralize exception handling with single handler using ErrorCode
  src/main/java/talkPick/batch/topic/adapter/TopicCacheManagerAdapter.java
  src/main/java/talkPick/batch/topic/exception/JVMCacheException.java
  src/main/java/talkPick/domain/member/adapter/out/MemberQueryRepositoryAdapter.java
  src/main/java/talkPick/domain/member/application/MemberCommandService.java
  src/main/java/talkPick/domain/member/application/MemberQueryService.java
  src/main/java/talkPick/domain/notice/adapter/out/NoticeQueryRepositoryAdapter.java
  src/main/java/talkPick/domain/notice/exception/NoticeNotFoundException.java
  src/main/java/talkPick/domain/topic/adapter/out/TopicLikeHistoryCommandRepositoryAdapter.java
  src/main/java/talkPick/domain/topic/adapter/out/TopicQueryRepositoryAdapter.java
  src/main/java/talkPick/domain/topic/exception/CategoryNotFoundException.java
  src/main/java/talkPick/domain/topic/exception/DuplicateLikeException.java
  src/main/java/talkPick/domain/topic/exception/KeywordNotFoundException.java
  src/main/java/talkPick/domain/topic/exception/TopicNotFoundException.java
  src/main/java/talkPick/external/kakao/application/KakaoOidcService.java
  src/main/java/talkPick/external/llm/adapter/LLMClientAdapter.java
  src/main/java/talkPick/external/llm/exception/LLMException.java
  src/main/java/talkPick/global/exception/handler/HealthCheckExceptionHandler.java
  src/main/java/talkPick/global/exception/handler/JVMCacheExceptionHandler.java
  src/main/java/talkPick/global/exception/handler/JwtExceptionHandler.java
  src/main/java/talkPick/global/exception/handler/KakaoExceptionHandler.java
  src/main/java/talkPick/global/exception/handler/LLMExceptionHandler.java
  src/main/java/talkPick/global/exception/handler/MemberExceptionHandler.java
  src/main/java/talkPick/global/exception/handler/NoticeExceptionHandler.java
  src/main/java/talkPick/global/exception/handler/RateLimitExceededExceptionHandler.java
  src/main/java/talkPick/global/exception/handler/SecurityExceptionHandler.java
  src/main/java/talkPick/global/exception/handler/TermExceptionHandler.java
  src/main/java/talkPick/global/exception/handler/TodayExceptionHandler.java
  src/main/java/talkPick/global/exception/handler/TopicExceptionHandler.java
  src/main/java/talkPick/global/healthCheck/api/DBHealthIndicator.java
  src/main/java/talkPick/global/healthCheck/api/UrlHealthIndicator.java
  src/main/java/talkPick/global/healthCheck/exception/HealthCheckException.java
  src/main/java/talkPick/global/rateLimiter/aspect/RateLimiterAspect.java
  src/main/java/talkPick/global/rateLimiter/exception/RateLimitExceededException.java
  src/main/java/talkPick/global/security/exception/AuthException.java
  src/main/java/talkPick/global/security/exception/RoleNotFoundException.java
  src/main/java/talkPick/global/security/exception/UnauthorizedException.java
  src/main/java/talkPick/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/talkPick/global/security/handler/ExceptionHandlerFilter.java
  src/main/java/talkPick/global/security/jwt/application/JwtTokenCommandCommandService.java
  src/main/java/talkPick/global/security/jwt/util/JwtGenerator.java
  src/main/java/talkPick/global/security/jwt/util/JwtProvider.java
  src/test/java/talkPick/topic/application/TopicCommandServiceTest.java
Labels: 🐶 M-ung, 🔨 Refactor

#173 [Refactor] Update Random topic course
  src/main/java/talkPick/batch/dummyData/scheduler/DummyDataScheduler.java
  src/main/java/talkPick/batch/topic/adapter/TopicCacheManagerAdapter.java
  src/main/java/talkPick/domain/admin/application/AdminTopicCommandService.java
  src/main/java/talkPick/domain/random/adapter/in/RandomCommandApi.java
  src/main/java/talkPick/domain/random/adapter/in/RandomCommandController.java
  src/main/java/talkPick/domain/random/adapter/in/RandomQueryApi.java
  src/main/java/talkPick/domain/random/adapter/in/RandomQueryController.java
  src/main/java/talkPick/domain/random/adapter/in/dto/RandomReqDTO.java
  src/main/java/talkPick/domain/random/adapter/out/RandomQueryRepositoryAdapter.java
  src/main/java/talkPick/domain/random/adapter/out/RandomTopicHistoryCommandRepositoryAdapter.java
  src/main/java/talkPick/domain/random/adapter/out/RandomTopicHistoryQueryRepositoryAdapter.java
  src/main/java/talkPick/domain/random/adapter/out/dto/RandomResDTO.java
  src/main/java/talkPick/domain/random/adapter/out/repository/RandomQuerydslRepository.java
  src/main/java/talkPick/domain/random/adapter/out/repository/RandomTopicHistoryJpaRepository.java
  src/main/java/talkPick/domain/random/adapter/out/repository/RandomTopicHistoryQuerydslRepository.java
  src/main/java/talkPick/domain/random/application/RandomCommandService.java
  src/main/java/talkPick/domain/random/application/RandomQueryService.java
  src/main/java/talkPick/domain/random/domain/Random.java
  src/main/java/talkPick/domain/random/domain/RandomTopicHistory.java
  src/main/java/talkPick/domain/random/exception/RandomNotFoundException.java
  src/main/java/talkPick/domain/random/exception/RandomTopicHistoryNotFoundException.java
  src/main/java/talkPick/domain/random/exception/TopicStatNotFoundException.java
  src/main/java/talkPick/domain/random/port/in/RandomCommandUseCase.java
  src/main/java/talkPick/domain/random/port/in/RandomQueryUseCase.java
  src/main/java/talkPick/domain/random/port/out/RandomQueryRepositoryPort.java
  src/main/java/talkPick/domain/random/port/out/RandomTopicHistoryCommandRepositoryPort.java
  src/main/java/talkPick/domain/random/port/out/RandomTopicHistoryQueryRepositoryPort.java
  src/main/java/talkPick/domain/search/adapter/in/TopicSearchApi.java
  src/main/java/talkPick/domain/today/adapter/out/TodayTopicCommandRepositoryAdapter.java
  src/main/java/talkPick/domain/today/adapter/out/dto/TodayTopicResDTO.java
  src/main/java/talkPick/domain/today/adapter/out/repository/TodayTopicQuerydslRepository.java
  src/main/java/talkPick/domain/topic/adapter/in/TopicQueryApi.java
  src/main/java/talkPick/domain/topic/adapter/in/TopicQueryController.java
  src/main/java/talkPick/domain/topic/adapter/out/TopicQueryRepositoryAdapter.java
  src/main/java/talkPick/domain/topic/adapter/out/TopicStatQueryRepositoryAdapter.java
  src/main/java/talkPick/domain/topic/adapter/out/dto/TopicResDTO.java
  src/main/java/talkPick/domain/topic/adapter/out/repository/TopicQuerydslRepository.java
  src/main/java/talkPick/domain/topic/application/TopicQueryService.java
  src/main/java/talkPick/domain/topic/domain/Topic.java
  src/main/java/talkPick/domain/topic/domain/TopicImage.java
  src/main/java/talkPick/domain/topic/domain/type/Keyword.java
  src/main/java/talkPick/domain/topic/port/in/TopicQueryUseCase.java
  src/main/java/talkPick/domain/topic/port/out/TopicQueryRepositoryPort.java
  src/main/java/talkPick/global/exception/handler/RandomExceptionHandler.java
Labels: 🐶 M-ung, 🔨 Refactor

#176 [Test] Test total API
  src/main/java/talkPick/domain/random/adapter/out/RandomTopicHistoryQueryRepositoryAdapter.java
  src/main/java/talkPick/domain/random/adapter/out/repository/RandomQuerydslRepository.java
  src/main/java/talkPick/domain/random/adapter/out/repository/RandomTopicHistoryJpaRepository.java
  src/main/java/talkPick/domain/random/domain/Random.java
  src/main/java/talkPick/domain/random/domain/type/RandomType.java
  src/main/java/talkPick/domain/today/adapter/out/dto/TodayTopicResDTO.java
  src/main/java/talkPick/domain/topic/adapter/out/dto/TopicResDTO.java
Labels: 🐶 M-ung, ✅ Test

#184 [Feature] 문의하기 API
  src/main/java/talkPick/domain/inquiry/adapter/in/InquiryCommandApi.java
  src/main/java/talkPick/domain/inquiry/adapter/in/InquiryCommandController.java
  src/main/java/talkPick/domain/inquiry/adapter/in/InquiryQueryApi.java
  src/main/java/talkPick/domain/inquiry/adapter/in/InquiryQueryController.java
  src/main/java/talkPick/domain/inquiry/adapter/in/dto/InquiryReqDto.java
  src/main/java/talkPick/domain/inquiry/adapter/out/InquiryCommandRepositoryAdapter.java
  src/main/java/talkPick/domain/inquiry/adapter/out/InquiryQueryRepositoryAdapter.java
  src/main/java/talkPick/domain/inquiry/adapter/out/dto/InquiryResDto.java
  src/main/java/talkPick/domain/inquiry/adapter/out/repository/InquiryJpaRepository.java
  src/main/java/talkPick/domain/inquiry/adapter/out/repository/InquiryQuerydslRepository.java
  src/main/java/talkPick/domain/inquiry/application/InquiryCommandService.java
  src/main/java/talkPick/domain/inquiry/application/InquiryQueryService.java
  src/main/java/talkPick/domain/inquiry/converter/InquiryConverter.java
  src/main/java/talkPick/domain/inquiry/domain/Inquiry.java
  src/main/java/talkPick/domain/inquiry/domain/type/InquiryType.java
  src/main/java/talkPick/domain/inquiry/port/in/InquiryCommandUseCase.java
  src/main/java/talkPick/domain/inquiry/port/in/InquiryQueryUseCase.java
  src/main/java/talkPick/domain/inquiry/port/out/InquiryCommandRepositoryPort.java
  src/main/java/talkPick/domain/inquiry/port/out/InquiryQueryRepositoryPort.java
  src/main/java/talkPick/domain/member/adapter/out/MemberCommandRepositoryAdapter.java
  src/main/java/talkPick/domain/member/adapter/out/MemberTermCommandRepositoryAdapter.java
  src/main/java/talkPick/domain/member/adapter/out/TermQueryRepositoryAdapter.java
  src/main/java/talkPick/domain/member/adapter/out/dto/MemberResDto.java
  src/main/java/talkPick/domain/member/application/MemberCommandService.java
  src/main/java/talkPick/domain/member/application/MemberQueryService.java
  src/main/java/talkPick/domain/member/port/out/MemberCommandRepositoryPort.java
  src/main/java/talkPick/domain/member/port/out/MemberTermCommandRepositoryPort.java
  src/main/java/talkPick/domain/term/port/out/TermQueryRepositoryPort.java
  src/main/java/talkPick/global/config/JacksonConfig.java
  src/main/java/talkPick/global/config/SpringDocOpenApiConfig.java
  src/main/java/talkPick/global/exception/ErrorCode.java
  src/main/java/talkPick/global/security/model/WhiteList.java
Labels: ✨ Feature, SHM🙂
