Repository Talk-Pick/TalkPick_Server, pull requests merged in 2025-07, with the labels that each got.

#116 [Feature] Set up a circuit breaker and connect it to the LLM server
  .github/PULL_REQUEST_TEMPLATE
  build.gradle
  src/main/java/talkPick/external/llm/adapter/LLMClientAdapter.java
  src/main/resources/application-local.yml
Labels: 🐶 M-ung, ✨ Feature

#118 [Refactor] Organize required APIs and remove unnecessary APIs
  src/main/java/talkPick/domain/admin/adapter/in/AdminCommandController.java
  src/main/java/talkPick/domain/admin/adapter/in/dto/AdminReqDTO.java
  src/main/java/talkPick/domain/admin/adapter/out/dto/AdminResDTO.java
  src/main/java/talkPick/domain/admin/application/AdminCommandService.java
  src/main/java/talkPick/domain/admin/application/AdminQueryService.java
  src/main/java/talkPick/domain/admin/application/AdminTopicCommandService.java
  src/main/java/talkPick/domain/admin/application/AuthCommandService.java
  src/main/java/talkPick/domain/admin/application/AuthQueryService.java
  src/main/java/talkPick/domain/admin/domain/Admin.java
  src/main/java/talkPick/domain/admin/domain/type/Role.java
  src/main/java/talkPick/domain/admin/validator/PasswordConstraintValidator.java
  src/main/java/talkPick/domain/admin/validator/ValidationMessages.java
  src/main/java/talkPick/domain/admin/validator/annotation/ValidPassword.java
  src/main/java/talkPick/domain/auth/application/query/AuthQueryService.java
  src/main/java/talkPick/domain/member/adapter/in/KakaoAuthController.java
  src/main/java/talkPick/domain/member/adapter/in/MemberCommandController.java
  src/main/java/talkPick/domain/member/adapter/out/MemberQueryRepositoryAdaptor.java
  src/main/java/talkPick/domain/member/application/KakaoOAuthHandler.java
  src/main/java/talkPick/domain/member/application/MemberCommandService.java
  src/main/java/talkPick/domain/member/application/MemberQueryService.java
  src/main/java/talkPick/domain/member/domain/Member.java
  src/main/java/talkPick/domain/member/exception/KaKaoOAuthException.java
  src/main/java/talkPick/domain/member/exception/MemberAlreadyExistsexception.java
  src/main/java/talkPick/domain/member/exception/MemberNotFoundException.java
  src/main/java/talkPick/domain/member/exception/MemberServiceException.java
  src/main/java/talkPick/domain/random/adapter/in/RandomCommandApi.java
  src/main/java/talkPick/domain/random/adapter/in/RandomCommandController.java
  src/main/java/talkPick/domain/random/adapter/in/RandomQueryApi.java
  src/main/java/talkPick/domain/random/adapter/in/RandomQueryController.java
  src/main/java/talkPick/domain/search/adapter/in/TopicSearchApi.java
  src/main/java/talkPick/domain/search/adapter/in/TopicSearchController.java
  src/main/java/talkPick/domain/search/application/TopicSearchQueryService.java
  src/main/java/talkPick/domain/search/port/in/TopicSearchQueryUseCase.java
  src/main/java/talkPick/domain/topic/adapter/in/TopicCommandApi.java
  src/main/java/talkPick/domain/topic/adapter/in/TopicCommandController.java
  src/main/java/talkPick/domain/topic/adapter/in/TopicQueryApi.java
  src/main/java/talkPick/domain/topic/adapter/in/TopicQueryController.java
  src/main/java/talkPick/domain/topic/application/TopicQueryService.java
  src/main/java/talkPick/external/llm/adapter/LLMClientAdapter.java
  src/main/java/talkPick/external/llm/constants/LLMConstants.java
  src/main/java/talkPick/global/config/CorsFilter.java
  src/main/java/talkPick/global/config/SpringDocOpenApiConfig.java
  src/main/java/talkPick/global/rateLimiter/aspect/RateLimiterAspect.java
  src/main/java/talkPick/global/security/config/SecurityConfig.java
  src/main/java/talkPick/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/talkPick/global/security/handler/ExceptionHandlerFilter.java
  src/main/java/talkPick/global/security/model/CustomUserDetails.java
  src/main/java/talkPick/global/security/model/WhiteList.java
  src/main/resources/application-local.yml
  src/test/java/talkPick/member/MemberCommandControllerTest.java
Labels: 🐞 BugFix, 🐶 M-ung, 🔨 Refactor

#139 [Refactor] Update api ent-point
  src/main/java/talkPick/domain/search/adapter/in/TopicSearchApi.java
Labels: 🐶 M-ung, 🔨 Refactor

#144 [Refactor] 카카오 로그인 API 개선
  src/main/java/talkPick/domain/member/adapter/in/KakaoAuthController.java
  src/main/java/talkPick/domain/member/adapter/in/MemberCommandController.java
  src/main/java/talkPick/global/security/model/WhiteList.java
Labels: 🔨 Refactor

#150 [Test] Test all APIs after inserting dummy data to the database
  src/main/java/talkPick/batch/dummyData/scheduler/DummyDataScheduler.java
  src/main/java/talkPick/batch/topic/adapter/TopicCacheManagerAdapter.java
  src/main/java/talkPick/domain/notice/adapter/in/NoticeQueryApi.java
  src/main/java/talkPick/domain/notice/adapter/in/NoticeQueryController.java
  src/main/java/talkPick/domain/notice/adapter/out/repository/NoticeQuerydslRepository.java
  src/main/java/talkPick/domain/random/adapter/in/RandomCommandApi.java
  src/main/java/talkPick/domain/random/adapter/out/dto/RandomResDTO.java
  src/main/java/talkPick/domain/search/adapter/in/TopicSearchApi.java
  src/main/java/talkPick/domain/search/adapter/out/TopicSearchHistoryQueryRepositoryAdapter.java
  src/main/java/talkPick/domain/search/application/TopicSearchQueryService.java
  src/main/java/talkPick/domain/topic/adapter/out/TopicQueryRepositoryAdapter.java
  src/main/java/talkPick/domain/topic/adapter/out/dto/TopicResDTO.java
  src/main/java/talkPick/global/config/CorsFilter.java
  src/main/java/talkPick/global/config/SpringDocOpenApiConfig.java
  src/main/java/talkPick/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/talkPick/global/security/model/WhiteList.java
  src/main/resources/application-local.yml
Labels: 🐶 M-ung, ✅ Test

#152 [Test] Test api using postman
  src/main/java/talkPick/batch/dummyData/scheduler/DummyDataScheduler.java
  src/main/java/talkPick/domain/random/adapter/in/RandomCommandApi.java
  src/main/java/talkPick/domain/random/adapter/in/RandomCommandController.java
  src/main/java/talkPick/domain/random/adapter/in/dto/RandomReqDTO.java
  src/main/java/talkPick/domain/random/adapter/out/RandomTopicHistoryCommandRepositoryAdapter.java
  src/main/java/talkPick/domain/random/application/RandomCommandService.java
  src/main/java/talkPick/domain/random/domain/RandomTopicHistory.java
  src/main/java/talkPick/domain/random/port/in/RandomCommandUseCase.java
  src/main/java/talkPick/domain/random/port/out/RandomTopicHistoryCommandRepositoryPort.java
  src/main/java/talkPick/domain/topic/adapter/in/TopicQueryApi.java
  src/main/java/talkPick/domain/topic/adapter/in/TopicQueryController.java
  src/main/java/talkPick/domain/topic/adapter/in/dto/TopicReqDTO.java
  src/main/java/talkPick/domain/topic/domain/TopicStat.java
  src/main/java/talkPick/global/config/CorsFilter.java
  src/main/java/talkPick/global/exception/ErrorCode.java
  src/main/java/talkPick/global/security/config/SecurityConfig.java
  src/main/java/talkPick/global/security/exception/RoleNotFoundException.java
  src/main/java/talkPick/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/talkPick/global/security/filter/TokenAuthentication.java
  src/main/java/talkPick/global/security/handler/ExceptionHandlerFilter.java
  src/main/java/talkPick/global/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/talkPick/global/security/jwt/JwtConfig.java
  src/main/java/talkPick/global/security/jwt/JwtProperties.java
  src/main/java/talkPick/global/security/jwt/util/JwtGenerator.java
  src/main/java/talkPick/global/security/jwt/util/JwtProvider.java
  src/main/java/talkPick/global/security/model/WhiteList.java
  src/main/java/talkPick/global/security/resolver/UserIdArgumentResolver.java
  src/main/resources/application-local.yml
Labels: 🐶 M-ung, ✅ Test

#159 [Fix] Fix Search Api
  src/main/java/talkPick/domain/search/adapter/out/TopicSearchHistoryQueryRepositoryAdapter.java
  src/main/java/talkPick/domain/search/application/TopicSearchQueryService.java
Labels: 🐞 BugFix, 🐶 M-ung

#162 refactor: Update parameter name - #160
  src/main/java/talkPick/domain/admin/application/AuthCommandService.java
  src/main/java/talkPick/domain/admin/port/in/AdminTopicQueryUseCase.java
  src/main/java/talkPick/domain/member/adapter/in/MemberCommandController.java
  src/main/java/talkPick/domain/member/adapter/in/MemberQueryController.java
  src/main/java/talkPick/domain/random/adapter/in/RandomCommandApi.java
  src/main/java/talkPick/domain/random/adapter/in/RandomCommandController.java
  src/main/java/talkPick/domain/search/adapter/in/TopicSearchApi.java
  src/main/java/talkPick/domain/today/adapter/in/TodayTopicCommandApi.java
  src/main/java/talkPick/domain/today/adapter/in/TodayTopicCommandController.java
  src/main/java/talkPick/domain/today/application/TodayTopicCommandService.java
  src/main/java/talkPick/domain/today/port/in/TodayTopicCommandUseCase.java
  src/main/java/talkPick/domain/topic/adapter/in/TopicCommandApi.java
  src/main/java/talkPick/domain/topic/application/TopicCommandService.java
  src/main/java/talkPick/domain/topic/port/in/TopicCommandUseCase.java
  src/main/java/talkPick/global/config/WebConfig.java
  src/main/java/talkPick/global/security/annotation/MemberId.java
  src/main/java/talkPick/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/talkPick/global/security/filter/TokenAuthentication.java
  src/main/java/talkPick/global/security/jwt/RefreshToken.java
  src/main/java/talkPick/global/security/jwt/dto/JwtResDTO.java
  src/main/java/talkPick/global/security/jwt/repository/RefreshTokenRepository.java
  src/main/java/talkPick/global/security/jwt/util/JwtGenerator.java
  src/main/java/talkPick/global/security/jwt/util/JwtProvider.java
  src/main/java/talkPick/global/security/jwt/util/RefreshTokenGenerator.java
  src/main/java/talkPick/global/security/resolver/MemberIdArgumentResolver.java
Labels: 🐶 M-ung, 🔨 Refactor
